Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ask', to: 'questions#ask', as: :ask
  get 'answer', to: 'questions#answer', as: :answer
  # If we were going to a static page, we would say "get 'pages/restaurants'"
  # Here, however, the page is generated by the method that we are going to code in answer.
end
